# Generated by Django 4.2.26 on 2026-03-26 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('member', 'Member')], default='member', max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('profile_image_url', models.URLField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('bio', models.TextField(blank=True)),
                ('speciality', models.CharField(blank=True, max_length=100)),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('qr_code', models.TextField(blank=True)),
                ('instructor', models.ForeignKey(blank=True, limit_choices_to={'role': 'staff'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_members', to='accounts.userprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
