# Generated by Django 4.2.26 on 2026-03-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_userprofile_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='target_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
    ]
