# Generated by Django 4.2.26 on 2026-03-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_dailytaskcompletion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalworkout',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
