# Generated by Django 4.2.26 on 2026-03-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0006_remove_dailytaskcompletion_weight_used_kg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietplan',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
