# Generated by Django 4.2.26 on 2026-03-28 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0007_dietplan_end_date_dietplan_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dietplan',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='dietplan',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='workoutplan',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='workoutplan',
            name='start_date',
        ),
    ]
