# Generated by Django 4.2.26 on 2026-03-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0008_remove_dietplan_end_date_remove_dietplan_start_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meal',
            options={'ordering': ['day', 'order', 'meal_type']},
        ),
        migrations.AddField(
            model_name='meal',
            name='video_url',
            field=models.URLField(blank=True),
        ),
    ]
