# Generated by Django 4.2.26 on 2026-03-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0009_alter_meal_options_meal_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresslog',
            name='height_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
    ]
