# Generated by Django 4.2.26 on 2026-03-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0010_progresslog_height_cm'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymealcompletion',
            name='calories_snapshot',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailymealcompletion',
            name='carbs_snapshot',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='dailymealcompletion',
            name='fat_snapshot',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='dailymealcompletion',
            name='protein_snapshot',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
    ]
