# Generated by Django 4.2.26 on 2026-03-28 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0011_dailymealcompletion_calories_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresslog',
            name='diet_compliance_pct',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progresslog',
            name='workout_compliance_pct',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
