# Generated by Django 4.2.26 on 2026-05-26 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0012_progresslog_diet_compliance_pct_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progresslog',
            name='diet_compliance_pct',
        ),
        migrations.RemoveField(
            model_name='progresslog',
            name='workout_compliance_pct',
        ),
    ]
