# Generated by Django 4.2.27 on 2026-03-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='allowed_tabs',
            field=models.JSONField(default=list),
        ),
    ]
