# Generated by Django 4.2.26 on 2026-03-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_membershipplan_allowed_tabs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membershipplan',
            options={'ordering': ['display_order', 'price']},
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='show_in_overview',
            field=models.BooleanField(default=True),
        ),
    ]
