# Generated by Django 4.2.26 on 2026-03-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_alter_membershipplan_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membershipplan',
            options={'ordering': ['price']},
        ),
        migrations.RemoveField(
            model_name='membershipplan',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='membershipplan',
            name='show_in_overview',
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='allowed_tabs',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
